#!/bin/bash

# Copyright 2009  Michiel van Wessem, Manchester, United Kingdom
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# based on http://www.gettingclever.com/2008/06/vacuum-your-firefox-3.html
# ffvaccuum is a bash script that cleans up your firefox4 databases.

# Make it being VERBOSE by default.
VERBOSE=${VERBOSE:-YES}

# set some bold/bright ANSI colours
red="\033[01;31m"
green="\033[01;32m"
blue="\033[01;34m"
normal="\033[00m"

# Make sure sqlite3 is installed on the system.
if [[ ! -x $(which sqlite3) ]]; then
    echo "sqlite3 not found or non executable..."
    exit 1
fi

# Make sure we are dealing with firefox 3 or higher.
ffmajor=$($(which firefox) --version | awk '{ print $3 }' | awk -F. '{ print $1}')
if [[ ${ffmajor} -lt 3 ]]; then
    echo "Firefox is not the right version, we need firefox3, firefox4 or newer..."
    exit 1
fi

# Before we start, let's make sure that the browser is no longer running.
if ps aux | grep -v grep | grep firefox; then
    echo "Error, Firefox appears to be still running."
    echo "Please shut down firefox /before/ cleaning the database."
    exit 1
fi

# Let's do the magic.
( cd ${HOME}/.mozilla/
  for browser in {firefox,seamonkey}; do

    if [[ -e ${browser} ]]; then
      ( cd $browser
        echo "Cleaning started on $browser"

        for profiles in *.*/ ; do
          ( cd "${profiles}"
            echo "  Found profile in \"${profiles}\". Start cleaning..."
 
            for database in *.sqlite; do
              if [[ ${VERBOSE} = "YES" ]]; then
                printf "%13s %-30s %10s %11s" Vaccuuming \"${database}\" ... 

                echo "VACUUM;" | sqlite3 "${database}" >/dev/null 2>&1
                status=$?

                if [[ ${status} -eq 0 ]]; then
                  echo -e "${blue}[ ${green}cleaned${blue} ]${normal}"
                else
                  echo -e "${blue}[ ${red}failed${blue}  ]${normal}"
                fi
              else
                echo "VACUUM;" | sqlite3 "${database}"
              fi  
            done
          )
        done
      )
    fi
  done
)

#EOF
